files:
  - source: content/commons/docs/en-us/**/*.md
    translation: content/commons/docs/%locale%/%original_file_name%
  - source: content/commons/navigation/en-us/**/*.yaml
    translation: content/commons/navigation/%locale%/%original_file_name%
